name: 'SentinelScan Security'
description: 'Verifica automaticamente vulnerabilidades e segredos expostos no código.'
author: 'Miguel Ferreira'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  target-dir:
    description: 'Directory to scan'
    required: true
    default: '.'
  output-file:
    description: 'Output file for report'
    required: false
    default: 'security_report.json'

runs:
  using: 'docker'
  image: 'Dockerfile'
  # O segredo está aqui: Forçamos o uso do Python e do script main.py
  entrypoint: 'python'
  args:
    - '/app/main.py'
    - ${{ inputs.target-dir }}
    - '--output'
    - ${{ inputs.output-file }}