name: 'Sentinel Security Scan'
description: 'Automated SAST and SCA security scanning for your pipeline.'
inputs:
  api-key:
    description: 'Your Sentinel API Key'
    required: false
  path:
    description: 'Path to scan'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: pip install requests
      shell: bash

    - name: Run Sentinel Scanner
      run: python ${{ github.action_path }}/sentinel.py --path ${{ inputs.path }}
      shell: bash