name: 'Sentinel Security Scan'
description: 'Automated SAST and SCA security scanning for your pipeline.'
inputs:
  api-key:
    description: 'Your Sentinel API Key'
    required: false
  path:
    description: 'Path to scan'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  # O segredo está aqui: Forçamos o uso do Python e do script main.py
  entrypoint: 'python'
  args:
    - '/app/main.py'
    - ${{ inputs.target-dir }}
    - '--output'
    - ${{ inputs.output-file }}